library(testthat)
library(data.table)
library(previsionio)

# test_check("previsionio")

# wd = getwd()

# test_active_file(paste0(wd, "/tests/testthat/test-project.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-connector.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-datasource.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-folder.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-dataset.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-experiment.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-pipeline.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-deployment.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-exporter.R"))

# test_active_file(paste0(wd, "/tests/testthat/test-exporter-delete.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-deployment-delete.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-pipeline-delete.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-experiment-delete.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-dataset-delete.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-folder-delete.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-datasource-delete.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-connector-delete.R"))
# test_active_file(paste0(wd, "/tests/testthat/test-project-delete.R"))
