# PREVISION.IO ENV VAR
pio_env   = "https://xxx.prevision.io"
pio_token = "***"

initPrevisionioClient(pio_token, pio_env)

# EXTERNAL DB ENV VAR
## CONNECTORS
SQL_CONNECTOR_HOST = "***"
SQL_CONNECTOR_PORT = 0
SQL_CONNECTOR_USER = "***"
SQL_CONNECTOR_PASS = "***"

HIVE_CONNECTOR_HOST = "***"
HIVE_CONNECTOR_PORT = 0
HIVE_CONNECTOR_USER = "***"
HIVE_CONNECTOR_PASS = "***"

HBASE_CONNECTOR_HOST = "***"
HBASE_CONNECTOR_PORT = 0
HBASE_CONNECTOR_USER = "***"
HBASE_CONNECTOR_PASS = "***"

HDFS_CONNECTOR_HOST = "***"
HDFS_CONNECTOR_PORT = 0
HDFS_CONNECTOR_USER = "***"
HDFS_CONNECTOR_PASS = "***"

S3_CONNECTOR_USER = "***"
S3_CONNECTOR_PASS = "***"

SFTP_CONNECTOR_HOST = "***"
SFTP_CONNECTOR_PORT = 0
SFTP_CONNECTOR_USER = "***"
SFTP_CONNECTOR_PASS = "***"

FTP_CONNECTOR_HOST = "***"
FTP_CONNECTOR_PORT = 0
FTP_CONNECTOR_USER = "***"
FTP_CONNECTOR_PASS = "***"

GCP_CREDENTIALS = fromJSON("gcp.json")

## DATA SOURCES
SQL_DATASOURCE_BASE = "***"
SQL_DATASOURCE_TABLE = "***"
SQL_DATASOURCE_REQUEST = "***"

HIVE_DATASOURCE_BASE = "***"
HIVE_DATASOURCE_TABLE = "***"
HIVE_DATASOURCE_REQUEST = "***"

S3_DATASOURCE_BUCKET = "***"
S3_DATASOURCE_PATH = "***"

SFTP_DATASOURCE_PATH = "***"

FTP_DATASOURCE_PATH = "***"
